version: '3.3'

services:

    mssql:
        image: microsoft/mssql-server-linux:2017-latest     
        container_name: mssql-server
        restart: always     
        volumes:
            - mssql-data:/var/opt/mssql
        ports:
            - "1433:1433"
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: password
   
volumes:    
    mssql-data:       
